jobs:
  build:
    docker:
      - image: cimg/node:16.16.0
    steps:
      - checkout
      - run: npm install --save-dev jest
      - run: npm install --save-dev babel-jest @babel/core @babel/preset-env
      - run: python -m http.server 8000
      - run:
          name: Run tests
          command: npm run test
