jobs:
  build:
    docker:
      - image: cimg/node:16.16.0
    steps:
      - checkout
      - run: 
          name: NPM config
          command: |
            npm install --save-dev jest
            npm install --save-dev babel-jest @babel/core @babel/preset-env
      - run:
          name: Run tests
          command: npm run test
