version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run: npm install --save-dev jest
      - run:
          name: Run tests
          command: npm run test