version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run:
          name: NPM install Jest
          command: "npm install --save-dev jest"
      - run:
          name: Test Jest
          command: "jest -v" 
      - run:
          name: Hello
          command: "npm run test"