version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12.16.0
    steps:
      - checkout
      - run: npm install --save-dev jest
      - run:
          name: Run tests
          command: npm run test